import type * as Monaco from "monaco-editor";
import { MONACO_SEMANTIC_TOKEN_TYPES } from "./semantic-tokens";

// Common lexical and semantic token roles. Hosts supply their own palette values.
export const MONACO_TOKEN_SYNTAX_ROLES: ReadonlyArray<readonly [string, string]> = [
  ["comment", "comment"],
  ["comment.documentation", "comment"],
  ["comment.doc", "documentation"],
  ["keyword", "keyword"],
  ["keyword.control", "keyword"],
  ["keyword.directive", "keyword"],
  ["keyword.import", "keyword"],
  ["keyword.return", "keyword"],
  ["string", "string"],
  ["string.escape", "string"],
  ["string.regexp", "regex"],
  ["string.regex", "regex"],
  ["string.value", "string"],
  ["string.key", "property"],
  ["number", "number"],
  ["number.float", "number"],
  ["number.hex", "number"],
  ["regexp", "regex"],
  ["regexp.escape", "regex"],
  ["regexp.escape.control", "regex"],
  ["identifier", "variable"],
  ["variable.other", "variable"],
  ["variable.predefined", "variable"],
  ["variable.readonly", "constant"],
  ["type.identifier", "type"],
  ["function", "function"],
  ["function.call", "function"],
  ["function.builtin", "function"],
  ["function.method", "function"],
  ["function.method.call", "function"],
  ["macro", "function"],
  ["method", "function"],
  ["variable", "variable"],
  ["parameter", "variable"],
  ["variable.parameter", "variable"],
  ["constant", "constant"],
  ["constant.builtin", "constant"],
  ["enumMember", "constant"],
  ["boolean", "boolean"],
  ["null", "null"],
  ["keyword.other", "keyword"],
  ["modifier", "keyword"],
  ["type", "type"],
  ["typeParameter", "type"],
  ["class", "type"],
  ["enum", "type"],
  ["struct", "type"],
  ["interface", "type"],
  ["namespace", "type"],
  ["module", "type"],
  ["module.builtin", "type"],
  ["property", "property"],
  ["property.readonly", "constant"],
  ["key", "property"],
  ["support.type.property-name", "property"],
  ["decorator", "attribute"],
  ["annotation", "attribute"],
  ["attribute", "attribute"],
  ["attribute.value", "string"],
  ["attribute.value.number", "number"],
  ["attribute.value.unit", "number"],
  ["attribute.value.hex", "number"],
  ["tag", "tag"],
  ["metatag", "tag"],
  ["metatag.content", "string"],
  ["attribute.name", "attribute"],
  ["delimiter", "punctuation"],
  ["delimiter.bracket", "punctuation"],
  ["bracket", "punctuation"],
  ["punctuation", "punctuation"],
  ["operator", "operator"],
  ["keyword.operator", "operator"],
  ["predefined", "constant"],
  ["constructor", "function"],
  ["event", "function"],
  ["label", "variable"],
  ["parameter.readonly", "constant"],
  ["string.value.json", "string"],
  ["string.key.json", "property"],
  ["number.json", "number"],
  ["keyword.json", "boolean"],
];

/** Styles whose meaning is independent of the host's palette. */
export function createMonacoTokenStyleRules(
  italicComments: boolean,
  italicStatics = false,
): Monaco.editor.ITokenThemeRule[] {
  return [
    { token: "emphasis", fontStyle: "italic" },
    { token: "strong", fontStyle: "bold" },
    ...MONACO_SEMANTIC_TOKEN_TYPES.flatMap((token) => {
      const fontStyle =
        token === "comment" && italicComments ? "italic strikethrough" : "strikethrough";
      return [
        { token: `${token}.deprecated`, fontStyle },
        { token: `${token}.readonly.deprecated`, fontStyle },
      ];
    }),
    ...(italicStatics
      ? ["property", "variable", "method", "function", "constant", "enumMember"].flatMap(
          (token) => [
            { token: `${token}.static`, fontStyle: "italic" },
            { token: `${token}.readonly.static`, fontStyle: "italic" },
            { token: `${token}.deprecated.static`, fontStyle: "italic strikethrough" },
            { token: `${token}.readonly.deprecated.static`, fontStyle: "italic strikethrough" },
          ],
        )
      : []),
  ];
}
